### ISSUE TITLE
Animation for apply?

### ISSUE THREAD

**Issue by lidavidm** [lidavidm/reduct-redux#138]
> The animation of application is great right up until the end when there is a discontinuity as it switches to the normal view of the next node. Do we need some general support so that we can do “perfect” animations? (might be more work than it’s worth)

**Comment by lidavidm** [comment]
>Maybe a better animation would be to get rid of the outer “application” border earlier. Once the argument has been subsituted, I don’t see why that should persist. Then it’s just a matter of growing the body to full size.

**Comment by lidavidm** [comment]
then we can get rid of the expand effect

**Comment by andrewcmyers** [comment]
Would also be good to tune up the motion of the argument so it heads straight into the parameter. Currently it seems to head a bit to the left of the parameter. Might be nice to have it then scale down to zero as it scales up from zero in all substituted positions.
