### ISSUE TITLE
Definition expansion improvements

### ISSUE THREAD

**Issue by lidavidm** [lidavidm/reduct-redux#161]
- [x] Ease-in
- [x] Longer delay before it starts
- [x] Show it animating from the sidebar
- [ ] When it first is available, prompt the user (level where you have to unfold to solve - early on in definitions)
- [ ] Explicit button? (peeled corner or magnifying glass or lightning bolt - how would this work for touch users though?)
- [ ] Test with touch devices

**Comment by EatingW** [comment]
Some new changes in branch def-expand. https://github.com/lidavidm/reduct-redux/tree/def-expand.
