### ISSUE TITLE
Respect newDefinedNames for references-with-holes

### ISSUE THREAD

**Issue by lidavidm** [lidavidm/reduct-redux#196]
This will be tricky - presumably we want to do some sort of unfold?

**Comment by andrewcmyers** [comment]
I don't quite understand what's proposed?

**Comment by lidavidm** [comment]
@andrewcmyers On level 143, defining `repeatAdd1` then clicking `repeatAdd1(9, 9)` will big-step the entire expression, which is inconsistent with other levels where evaluating an application of a function defined for the first time on that level will small-step through the evaluation.
