### ISSUE TITLE
Repeat needs 3 holes; apply level needs 2 holes

### ISSUE THREAD

**Issue by lidavidm** [lidavidm/reduct-redux#222]

**Comment by andrewcmyers** [comment]
I don't think I agree with having repeat have 3 holes.

**Comment by lidavidm** [comment]
Okay. In that case if we are to black-box repeat, then essentially it would
never do anything except inside an apply block, in which case it would be
stepped over?

**Comment by andrewcmyers** [comment]
Hmm. Maybe repeat with 3 holes is the right thing to do. So repeat n f x gives you
```
f(f(f(...(f(x))))
<-- n -->
```

**Comment by lidavidm** [comment]
It could also take two parameters as well, simply giving you `lambda x. f(f(f...f(x)))`.
